### ISSUE TITLE
Doesn't restart on timeout error

### ISSUE THREAD

**Issue by CarlosVonEsteban** [persepolisdm/persepolis#1074]
Persepolis Version: 5.0.1
Operating System: Linux (Manjaro)
Desktop Environment: KDE Plasma
How do you install Persepolis?: repository 

Log:
2025-05-16 22:52:59,566 - Persepolis - ERROR - Connection error - HTTPSConnectionPool(host='██████████', port=443): Read timed out.

2025-05-16 22:53:04,958 - Persepolis - ERROR - Connection error - HTTPSConnectionPool(host='██████████', port=443): Read timed out.

2025-05-16 22:54:18,817 - Persepolis - ERROR - Connection error - HTTPSConnectionPool(host='██████████', port=443): Read timed out.

2025-05-16 22:56:02,885 - Persepolis - ERROR - Connection error - HTTPSConnectionPool(host='██████████', port=443): Read timed out

The file I am downloading is large file (over 9GiB). The current "solution" is to manually resume the download every few hours.

**Comment by alireza-amirsamimi** [comment]
Thank you for reporting this bug. Please update. Your version is very old and many bugs have been fixed so far. If the new version is not in your distribution's repositories, I recommend using the [AUR](https://aur.archlinux.org/packages/persepolis-git) version.

**Comment by CarlosVonEsteban** [comment]
Just tried version 5.1.1 from the AUR, same issue persists
status: error
connections: 0

**Comment by alireza-amirsamimi** [comment]
I confirm the existence of this bug. I will try to fix this issue in the next version. Thank you for reporting this bug.

**Comment by alireza-amirsamimi** [comment]
I made some changes to the code and settings to improve this problem. In my tests, the situation improved. To test, please update Persepolis via [AUR](https://aur.archlinux.org/packages/persepolis-git) and open the preferences window from the edit menu and from the download options tab change the wait period between retries value to 5 and change the timeout value to 10 and click the ok button.

![Image](https://github.com/user-attachments/assets/7d91ec62-2067-4c8b-a04a-4fc51fca7e01)

**Comment by CarlosVonEsteban** [comment]
Apologies for the late reply. After installing the new patch a few days ago, my downloads have been going much better. Thank you

**Comment by alireza-amirsamimi** [comment]
@CarlosVonEsteban Thanks for your feedback🙏
