### ISSUE TITLE
Fatal Error:Failed to execute script Persepolis Download Manager

### ISSUE THREAD

**Issue by nobody0525** [persepolisdm/persepolis#342]
Operating System: Window 10
Persepolis Version: persepolis_2_4_2_windows_64bit
When I uses Persepolis Download Manager Integration in Chrome version  61.0.3163.91(64bit) to download a file, the PDM runs and displays a popup window showing"Fatal Error:Failed to execute script Persepolis Download Manager" and I can't download the file.
I don't know what that means and how to fix it.

**Comment by SawaraNazo** [comment]
I also have the same question. When I try to download something on chrome, the extension wants to arouse the application, at this time, it will prompt me this.

![snipaste_20171203_084638](https://user-images.githubusercontent.com/31041465/33521279-bcf2abc6-d808-11e7-821e-c046947698a6.png)

It will fail to arouse the application.
But when I directly copy the link to the application, the download works properly.

I'm a new user of this. I download the extension in the chrome store. And I have set the extension in "help -> browser integration -> chrome", but it just tell me "Done!". I don't know what it "Done!", and whether it "Done!". So I hesitate to ask this issue. I'm very fortunate that it is not my own question (should be happy or sad இ௰இ)

Wait for your reply.

**Comment by alireza-amirsamimi** [comment]
we had some big! changes in persepolis and in extension recently. and this is caused this problem:)
We will release a new update very very soon( version 3.0.0) and it will compatible with chrome and firefox extensions.
Thanks for asking

**Comment by LuzMasonj** [comment]
I have this problem too.Waiting for the new version.

**Comment by jennygarden** [comment]
The new version of the PDM still has this problem. As a new user, I have no idea of how to fix it ... A little sad

**Comment by dddeveloperrr** [comment]
@jennygarden which version do you use??

**Comment by Livy-Inverse** [comment]
The bug still presents on:
- Windows 10 1809 x64
- PDM 310 x64
- Chrome 74.0.3729.131 (Official Build) (64-bit)

No problem on Linux.

**Comment by FahadYousafMahar** [comment]
I am also getting that same error and youtube videos aren't being downloaded.
Though other downloads are being captured and downloaded successfully.

Windows 10 1809 x64
PDM 310 x64
Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by pratikchandrani** [comment]
The same error is still faced while installing chrome extention

**Comment by blue126** [comment]
I am having the same problem as of today when trying to install the google chrome extension.

**Comment by WntFlm** [comment]
just same problem occurs at win10 Chrome

**Comment by crimx** [comment]
Same here on win10 x64. Re-installed the lastest version of both didn't help.

**Comment by eLv1976** [comment]
> I am also getting that same error and youtube videos aren't being downloaded.
> Though other downloads are being captured and downloaded successfully.
> 
> Windows 10 1809 x64
> PDM 310 x64
> Version 74.0.3729.157 (Official Build) (64-bit)

I am also have the same problem.

**Comment by derryck404** [comment]
⚠The bug still presents on:

- Windows 10 1903 x64
- PDM 3.1.0 x64
- Chrome  76.0.3809.87 (Official Build) (64-bit)

@alireza-amirsamimi

**Comment by alireza-amirsamimi** [comment]
Hello
I fixed this bug.
Thanks for reporting :+1:

**Comment by gamgamstylep** [comment]
still the same error with chrome and firefox (windows) 

![2019-08-21 08_45_15-Window](https://user-images.githubusercontent.com/43586166/63408797-1eee1e80-c3f0-11e9-9de2-b22e7e1184c0.png)
![2019-08-21 08_45_48-Window](https://user-images.githubusercontent.com/43586166/63408803-21507880-c3f0-11e9-938e-478f59a9dae7.png)

Persepolis Download Manager 3.1.0 (64bit)
