### ISSUE TITLE
UI Issues on 4K Displays

### ISSUE THREAD

**Issue by MRdevX** [persepolisdm/persepolis#348]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 17.10
* Desktop Environment(For GNU/Linux and BSD users):  Gnome
* Persepolis Version: 3.0.0
* How do you install Persepolis? Repositories (apt-get)

There are some graphic issues on 4K displays.

- menu icons are very tiny
- default element sizes are not suitable for this resolution

![screenshot from 2017-12-13 16-53-21](https://user-images.githubusercontent.com/13729592/33941102-a6c9bf94-e026-11e7-8c62-124b97e09f88.png)
![screenshot from 2017-12-13 16-52-56](https://user-images.githubusercontent.com/13729592/33941103-a70d7f22-e026-11e7-9ef1-c0b2781535a5.png)
![screenshot from 2017-12-13 16-52-34](https://user-images.githubusercontent.com/13729592/33941104-a73b5384-e026-11e7-8457-8b4e6abd5f01.png)
![screenshot from 2017-12-13 10-50-02](https://user-images.githubusercontent.com/13729592/33941106-a76b2aa0-e026-11e7-9814-305d4f77a19d.png)
![screenshot from 2017-12-13 10-26-41](https://user-images.githubusercontent.com/13729592/33941107-a79e99da-e026-11e7-8597-ae26521b0af2.png)

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting

**Comment by alireza-amirsamimi** [comment]
I fixed bugs!
progress window has been corrected.
In next version, you can change the icon size in preferences window(default is 32).
Thanks for reporting :)

**Comment by MRdevX** [comment]
thanks for upgrade and adding the feature to change the icon sizes, it's make it really polished on my desktop :) .
 but i still have some UI issues as you can see in these screenshots : 
some of text colors are not compatible with dark theme.
![screenshot from 2017-12-19 10-18-28](https://user-images.githubusercontent.com/13729592/34144326-47edbd3e-e4a6-11e7-9243-83b1f68f5a00.png)
minimum window size is not suitable for 4k display.
![screenshot from 2017-12-19 10-18-07](https://user-images.githubusercontent.com/13729592/34144327-4834587a-e4a6-11e7-86be-051e9a95d29a.png)

thanks in advance

**Comment by alireza-amirsamimi** [comment]
@MR612 
Hello
I added piece of code for solving persepolis's issue with 4K displays.
Can you test it, please? :)
[Read this link for installing persepolis from source.](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction-fa)
Please make sure that all dependencies is installed on your system :)

**Comment by MRdevX** [comment]
@alireza-amirsamimi 
Yes, Problem is Solved \m/
Thank You :)
FYI : I'm using Manjaro-Deepin right now.

**Comment by alireza-amirsamimi** [comment]
@MR612 
Thanks for testing :)
So I close the issue :)

**Comment by xsoheilalizadeh** [comment]
4K Issues still is there.
![Screenshot from 2019-04-26 02-34-18](https://user-images.githubusercontent.com/22220356/56787923-010b0700-67cc-11e9-8cc3-e8bdcfb01d9e.png)
![Screenshot from 2019-04-26 02-35-00](https://user-images.githubusercontent.com/22220356/56787926-023c3400-67cc-11e9-90d5-cef10205e670.png)
