### ISSUE TITLE
Cannot download files from Google Drive

### ISSUE THREAD

**Issue by handoi987654** [persepolisdm/persepolis#559]
**System Details:**
* Operating System: DeepIn OS 15.6
* Distro(For GNU/Linux and BSD users): Debian
* Desktop Environment(For GNU/Linux and BSD users): DDE
* Persepolis Version: 3.1.0
* How do you install Persepolis? .DEB package

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

**Comment by meichengg** [comment]
has this bug been fixed at this moment? @JafarAkhondali

**Comment by ghost** [comment]
the  issue is still there,

browser : Opera

i already match all cookies and user agent, but it seems not allowed by google drive

**Comment by 3xploiton3** [comment]
so many downloader linux cannot resume file from google drive

**Comment by ShrirajHegde** [comment]
XDM can download it fine
